version: '3'

services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airtribe
    ports:
      - "3300:3306" # you can change your localhost port to 3306 if you want, I did 3300 because I already have a mysql server running on 3306 port on my local machine
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - airtribe-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=airtribe
    networks:
      - airtribe-network

volumes:
  db_data:
    driver: local

networks:
  airtribe-network:
    driver: bridge
